[package]
name = "libuv-sys-lite"
version = "1.48.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/nathanwhit/libuv-sys-lite"
description = "Tiny, raw bindings to libuv without linking to it"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
