name: ci
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: cargo test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup libuv
        id: libuv
        run: |
          curl -O https://dist.libuv.org/dist/v1.48.0/libuv-v1.48.0.tar.gz
          tar -xzvf libuv-v1.48.0.tar.gz
          cd libuv-v1.48.0
          mkdir -p build
          (cd build && cmake -DCMAKE_BUILD_TYPE=Release -DLIBUV_BUILD_TESTS=OFF ..)
          if [ $RUNNER_OS = "Windows" ]; then
            cmake --build build --config Release
          else
            cmake --build build
          fi
          cat build/cmake_install.cmake
          ls -la build
          if [ $RUNNER_OS = "Windows" ]; then
            cmake --install build
            echo "LIBUV_LIB_PATH=C:\Program Files (x86)\libuv\lib" >> $GITHUB_ENV
            echo "LIBUV_INCLUDE_PATH=C:\Program Files (x86)\libuv\include" >> $GITHUB_ENV
          else
            sudo cmake --install build
          fi
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo test