name: ci
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: cargo test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup libuv
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh # for bash
          ./vcpkg install libuv
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo test --all-features
