name: ci
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: cargo test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup libuv
        id: libuv
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh # for bash
          echo '{"dependencies": ["libuv"],"overrides":[{"name": "libuv","version": "1.46.0"}],"builtin-baseline": "76d153790caf0592fce8fc4484aa6db18c7d00d4"}' >> ./vcpkg.json
          ./vcpkg install
          arch=$(echo "$RUNNER_ARCH" | tr '[:upper:]' '[:lower:]')
          echo "arch is $arch"
          case "$RUNNER_OS" in
            macOS)
              os=osx;;
            Linux)
              os=linux;;
            Windows)
              os=windows;;
          esac
          echo "os is $os"
          PKG_CONFIG_PATH="$(pwd)/installed/$arch-$os/lib/pkgconfig"
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH is $PKG_CONFIG_PATH"
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo test --all-features
