name: ci
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: cargo test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup libuv
        id: libuv
        run: |
          curl -O https://dist.libuv.org/dist/v1.48.0/libuv-v1.48.0.tar.gz
          tar -xzvf libuv-v1.48.0.tar.gz
          cd libuv-v1.48.0
          mkdir -p build
          (cd build && cmake -DCMAKE_BUILD_TYPE=Release ..)
          cmake --build build
          cmake --install build
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo fmt --check
      - run: cargo clippy
      - run: cargo test
